# 时空双维度Cross-Parent Attention完整配置
# 已集成到ForecastIT_MAIN.py中

data:
  root: ../data/MYDATA
  data_file: data\MYDATA\data.npz
  index_file: data\MYDATA\index.npz
  node_ids_path: data\MYDATA\node_ids.txt
  steps_per_day: 288
  in_channels: 3
  pred_len: 12

model:
  num_nodes: 30
  d_model: 160
  n_heads: 4
  n_layers: 3
  pred_len: 12
  tod_emb_dim: 24       
  dow_emb_dim: 24     
  undirected_diffusion: true  
  aapt:
    channels: 16              
    norm: sym           

  cluster_spa:
    use: true             
    gate_bias: 0.0           
    allow_self: true       
    assign_path: data/MYDATA/key_clusters.txt
    soft_bias_beta: 1.0     
    temperature: 0.8        
    layers: [2]            
    residual_alpha: 0.2    

  use_gcn: true
  gcn_order: 2
  gcn_out: 64
  adj_path: data/MYDATA/adj_mx.pkl
  adj_sub_path: data/MYDATA/adj_mx_sub.pkl


  time_key_cluster:
    num_clusters: 4
    assign_path: data/MYDATA/key_clusters.txt

  dropout: 0.1
  
  fine_grain:
    enable: true
    fine_indices: [0, 1, 2] 
    
    temporal_refine:
      type: "cross_parent"    
      kv_source: "hidden"   
      attn_heads: 4
      dropout: 0.1
      layers: 2
      ff_ratio: 2
      causal: false
      
    spatial_refine:
      type: "cross_parent"   
      kv_source: "hidden"    
      heads: 2
      dropout: 0.1
      
    parents:
      use_multi: true
      coarse_pool: [7, 8, 5, 6] 
      M: [[0.6,0.2,0.1,0.1],
          [0.3,0.3,0.2,0.2], 
          [0.5,0.2,0.2,0.1]]
      
    fusion:
      type: "gate"
      hidden_ratio: 2
      
    projector:
      type: "linear"
      hidden_ratio: 2
      
    gate:
      use_delta_residual: true
      method: "sigmoid"


train:
  batch_size: 32
  lr: 0.0001
  epochs: 2
  early_stop: 30
  weight_decay: 0.001
  milestones: [50, 100, 150]
  lr_decay_rate: 0.001
  save_dir: ./saved_models_temporal_spatial
  loss: huber
  patience: 20
  min_delta: 0.0
  num_workers: 0
  grad_clip: 5.0
  seed: 42
  dropout: 0.2,  

  monitor: "coarse_rmse"   
